version: 1
export: false
files:
  - .env
  - .env.local
  - ./backend/.env
  - ./worker/video-stt-worker/.env
env:
  MULTIPOST_DATABASE_URL:
  APP_URL:
  APP_SECRET:
  INTERNAL_SECRET:
  TWOSOMEREN_BASE_URL:
  AUTH_SECRET:
  AUTH_GITHUB_ID:
  AUTH_GITHUB_SECRET:
  AUTH_GOOGLE_ID:
  AUTH_GOOGLE_SECRET:
  AUTH_MAILGUN_KEY:
  AUTH_MAILGUN_FROM:
  AUTH_URL:
  JINA_API_KEY:
  TIKHUB_API_KEY:
  DEEPSEEK_BASE_URL:
  DEEPSEEK_API_KEY:
  DEEPSEEK_MODEL:
  OPENAI_API_KEY:
  OPENAI_BASE_URL:
  WORKER_BASE_URL:
  SEEDE_API_TOKEN:
  SEEDE_WEBHOOK_URL:
  BITIFUL_OSS_ENDPOINT:
  BITIFUL_OSS_ACCESS_KEY:
  BITIFUL_OSS_SECRET_KEY:
  BITIFUL_OSS_BUCKET:
  BITIFUL_OSS_CDN_URL:
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY:
  STRIPE_SECRET_KEY:
  STRIPE_WEBHOOK_SECRET:
  TIKTOK_CLIENT_KEY:
  TIKTOK_CLIENT_SECRET:
  TIKTOK_REDIRECT_URI:
  X_CLIENT_ID:
  X_CLIENT_SECRET:
  X_CODE_VERIFIER:
  X_REDIRECT_URI:
  TASK_CRON:
  REFRESH_ACCOUNT_CRON:
  CHECK_PUBLISH_STATUS_CRON:
  MODE:
  FACEBOOK_CLIENT_ID:
  FACEBOOK_CLIENT_SECRET:
  FACEBOOK_CONFIG_ID:
  FACEBOOK_REDIRECT_URI:
  LEAPERONE_API_BASE_URL:
  LEAPERONE_API_KEY:
  VIDEO_EXTRACT_API_URL:
  VIDEO_EXTRACT_API_KEY:
