version: "3.8"
services:
  multipost:
    image: registry.cn-hongkong.aliyuncs.com/leaperone/multipost:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: final
      args:
        - POSTHOG_API_KEY=${POSTHOG_API_KEY}
        - POSTHOG_MULTIPOST_ENV_ID=${POSTHOG_MULTIPOST_ENV_ID}
        - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
    environment:
      - NEXT_PUBLIC_BASE_PATH=https://multipost.app

  multipost-backend:
    image: registry.cn-hongkong.aliyuncs.com/leaperone/multipost:backend-latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: backend

  video-stt-worker:
    image: registry.cn-hongkong.aliyuncs.com/leaperone/multipost:video-stt-worker-latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: video-stt-worker
