version: "3.8"
services:
  multipost:
    image: registry.cn-hongkong.aliyuncs.com/leaperone/multipost:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: final
      args:
        - POSTHOG_API_KEY=${POSTHOG_API_KEY}
        - POSTHOG_MULTIPOST_ENV_ID=${POSTHOG_MULTIPOST_ENV_ID}
        - NEXT_PUBLIC_POSTHOG_KEY=${NEXT_PUBLIC_POSTHOG_KEY}
        - NEXT_PUBLIC_POSTHOG_HOST=${NEXT_PUBLIC_POSTHOG_HOST}
        - NEXT_PUBLIC_SENTRY_DSN=${NEXT_PUBLIC_SENTRY_DSN}
        - NEXT_PUBLIC_SENTRY_ENVIRONMENT=${NEXT_PUBLIC_SENTRY_ENVIRONMENT}
        - SENTRY_URL=${SENTRY_URL}
        - SENTRY_ORG=${SENTRY_ORG}
        - SENTRY_PROJECT=${SENTRY_PROJECT}
        - SENTRY_RELEASE=${SENTRY_RELEASE}
      secrets:
        - sentry_auth_token
    environment:
      - NEXT_PUBLIC_BASE_PATH=https://multipost.app

  multipost-backend:
    image: registry.cn-hongkong.aliyuncs.com/leaperone/multipost:backend-latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: backend

  video-stt-worker:
    image: registry.cn-hongkong.aliyuncs.com/leaperone/multipost:video-stt-worker-latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: video-stt-worker

secrets:
  sentry_auth_token:
    environment: SENTRY_AUTH_TOKEN
