version: "3.8"
services:
  multipost:
    image: registry.cn-hongkong.aliyuncs.com/leaperone/multipost:latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      - NEXT_PUBLIC_BASE_PATH=https://multipost.app

  multipost-backend:
    image: registry.cn-hongkong.aliyuncs.com/leaperone/multipost:backend-latest
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: backend


  multipost-backend:
    image: registry-vpc.cn-hongkong.aliyuncs.com/leaperone/multipost:backend-latest
    restart: always
    env_file:
      - multipost.env
    networks:
      - multipost