name: Trigger Deploy And Pr Check

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
      - master
      - release-candidate
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:
    inputs:
      ref:
        description: '部署的分支或标签'
        required: true
        default: 'main'
      message:
        description: '部署说明'
        required: false
        default: '手动触发部署'
      author:
        description: '触发者'
        required: false
        default: 'manual trigger'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Get first line of commit message
        id: commit
        run: |
          # 限制输入消息的长度为72个字符
          input_message=$(echo "${{ inputs.message }}" | cut -c 1-72)
          commit_message=$(echo "${{ github.event.head_commit.message }}" | cut -c 1-72)
          message="${commit_message:-$input_message}"
          first_line=$(echo "$message" | sed -n '1p' | sed 's/["\]/\\&/g')
          echo "first_line=${first_line}" >> $GITHUB_OUTPUT

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: leaperone/leaperone-releases
          event-type: deploy-multipost
          client-payload: '{
            "ref": "${{ github.ref_name }}",
            "message": "${{ steps.commit.outputs.first_line }}",
            "author": "${{ github.actor || inputs.author }}"
          }'
